name: pcb_image

on:
  push:
    branches:
      - main

jobs:
  render-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # needed to push to repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render PCB image Bottom board
        uses: linalinn/kicad-render@main
        with:
          pcb_file: "Hardware/pneumatic Backpack v3.0/pneumatic Backpack v3.0.kicad_pcb"
          output_path: ${{ github.workspace }}/images/bottom
          background: transparent
      - name: Render PCB image Top Board
        uses: linalinn/kicad-render@main
        with:
          pcb_file: "Hardware/pneumatic Backpack v3.1/pneumatic Backpack v3.1.kicad_pcb"
          output_path: ${{ github.workspace }}/images/top
          background: transparent

      - name: Commit rendered images
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add images/*
          git diff --staged --quiet || git commit -m "Auto-update PCB renders [skip ci]"
          git push
